create table if not exists roles
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
);

create table if not exists users
(
    id       integer generated by default as identity
        primary key,
    email    varchar(255) not null unique ,
    name     varchar(255) not null,
    password varchar(255) not null,
    phone    varchar(255) not null,
    role_id  integer references roles
);

create table photos
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
);

create table engine
(
    id            integer generated by default as identity
        primary key,
    engine_type   varchar(255),
    engine_power  varchar(255),
    engine_volume varchar(255),
    name          varchar(255)
);

create table body
(
    id   serial
        primary key,
    name varchar(255)
);

create table brands
(
    id   serial
        primary key,
    name varchar(255)
);

create table cars
(
    id           integer generated by default as identity
        primary key,
    color        varchar(255),
    mileage      varchar(255),
    model        varchar(255),
    transmission varchar(255),
    gear         varchar(255),
    year         varchar(255),
    brand_id     integer
        references brands,
    engine_id    integer
        references engine,
    body_id      integer
        references body
);

create table advertisements
(
    id          integer generated by default as identity
        primary key,
    date        timestamp,
    description text,
    price       varchar(255),
    status      boolean not null,
    car_id      integer
        constraint advertisements_cars_id_fkey
            references cars
            on delete cascade,
    user_id     integer
        constraint advertisements_users_id_fkey
            references users
            on delete cascade,
    city        varchar(255)
);


create table advertisements_photos
(
    advertisement_id integer not null
        references advertisements,
    photos_id        integer not null
        references photos
);

